package com.processVisualisation.virtualKitchen.restclient.config;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * Binds configuration properties under the {@code ai.drawthings} prefix,
 * including the base URL, generation endpoint, output image dimensions, and
 * request timeout used to call a self-hosted Draw Things server. Getters
 * and setters are generated by Lombok's {@link Data} annotation.
 */
@Data
@Component
@ConfigurationProperties(prefix = "ai.drawthings")
public class DrawThingsProperties {

    private String baseUrl;
    private String endpoint;
    private Integer width ;
    private Integer height ;
    private Long timeoutMs;
}
