package com.processVisualisation.virtualKitchen.restclient.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import lombok.Data;

/**
 * Binds configuration properties under the {@code ai.gemini} prefix,
 * including the API key, base URL, chat/image endpoints, default and image
 * models, and request timeout used to call Google's Gemini API. Getters and
 * setters are generated by Lombok's {@link Data} annotation.
 */
@Data
@Component
@ConfigurationProperties(prefix = "ai.gemini")
public class GeminiProperties {

    private String apiKey;
    private String baseUrl;
    private String chatEndpoint;
    private String defaultModel;
    private String imageModel;
    private Long timeoutMs;
    private Cache cache = new Cache();
    private Tts tts = new Tts();

    /**
     * Speech generation ({@code GeminiTtsProvider}). Shares the API key, base URL and
     * {@code generateContent} endpoint above, so Gemini is configured in exactly one place.
     */
    @Data
    public static class Tts {
        /** Fallback model id when the registry entry does not name one. */
        private String model = "gemini-2.5-flash-preview-tts";
        /** Prebuilt voice name (e.g. Kore, Puck, Charon). */
        private String voice = "Kore";
        /** Gemini TTS returns 16-bit mono little-endian PCM at this rate. */
        private int sampleRateHz = 24000;
        /** Optional style instruction prepended to the text, e.g. "Say in a calm, friendly voice:". */
        private String stylePrompt;
    }

    /**
     * Explicit context caching ({@code cachedContents}) for requests that opt in via
     * {@code AIRequest.cacheSystemPrompt}: the system prompt is stored once on Gemini's side and
     * referenced by name instead of being re-sent and re-billed at the full input rate.
     */
    @Data
    public static class Cache {
        private boolean enabled = false;
        private String endpoint = "/v1beta/cachedContents";
        /** Lifetime of a created cache; storage is billed per token-hour while it lives. */
        private long ttlSeconds = 3600;
        /** A cache this close to expiry is treated as expired, so a request never races its deletion. */
        private long refreshMarginSeconds = 120;
        /** After a failed creation, how long to send the system prompt inline before trying again. */
        private long failureBackoffSeconds = 300;
    }
}