package com.processVisualisation.virtualKitchen.restclient.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import lombok.Data;

/**
 * Binds configuration properties under the {@code ai.ollama} prefix,
 * including the base URL, chat endpoint, default model, request timeout,
 * context window and keep-alive used to call a locally or self-hosted Ollama
 * server. Getters and setters are generated by Lombok's {@link Data} annotation.
 */
@Data
@Component
@ConfigurationProperties(prefix = "ai.ollama")
public class OllamaProperties {

    private String baseUrl;
    private String chatEndpoint;
    private String defaultModel;
    private Long timeoutMs;

    /**
     * Context window (prompt + output tokens). Ollama's own default is only 2K–4K and it silently drops the
     * start of a longer prompt, so this must comfortably exceed the generation system prompt. Keep it constant:
     * a different value per request forces Ollama to reload the model and discard its prompt cache.
     */
    private Integer numCtx = 32768;

    /** How long Ollama keeps the model (and its cached prompt prefix) loaded after a request, e.g. "30m". */
    private String keepAlive = "30m";
}