package com.processVisualisation.virtualKitchen.restclient.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import lombok.Data;

/**
 * Binds configuration properties under the {@code ai.ollama} prefix,
 * including the base URL, chat endpoint, default model, and request timeout
 * used to call a locally or self-hosted Ollama server. Getters and setters
 * are generated by Lombok's {@link Data} annotation.
 */
@Data
@Component
@ConfigurationProperties(prefix = "ai.ollama")
public class OllamaProperties {

    private String baseUrl;
    private String chatEndpoint;
    private String defaultModel;
    private Long timeoutMs;
}