package com.processVisualisation.virtualKitchen.restclient.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import lombok.Data;

/**
 * Binds configuration properties under the {@code ai.openai} prefix,
 * including the API key, base URL, chat endpoint, default model, and
 * request timeout used to call OpenAI's API. Getters and setters are
 * generated by Lombok's {@link Data} annotation.
 */
@Data
@Component
@ConfigurationProperties(prefix = "ai.openai")
public class OpenAIProperties {

    private String apiKey;
    private String baseUrl;
    private String chatEndpoint;
    private String defaultModel;
    private Long timeoutMs;
}
